theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: StuckOverFlow website
description: We try to study tags on YouTube videos
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
