theme: jekyll-theme-minimal
title: StuckOverFlow website
description: We try to study tags on YouTube videos
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
