remote_theme: pages-themes/time-machine@v0.2.0
title: StuckOverFlow website 
description: We try to study tags on YouTube videos
show_downloads: True
navigation:
  - title: Home
    url: https://germouche.github.io/ada-template-website/
  - title: Example
    url: example
